name: duels
version: '1.0-SNAPSHOT'
main: sh.harold.duels.DuelsPlugin
bootstrapper: sh.harold.duels.DuelsBootstrapper
api-version: '1.21'
dependencies:
  bootstrap:
    Fulcrum:
      load: BEFORE
      required: true
  server:
    Fulcrum:
      load: BEFORE
      required: true
